[build]
command = "pnpm generate"
publish = "dist"

[build.environment]
NODE_VERSION = "18.18.2"

[context.production.environment]
ANALYZE = "true"

[context.deploy-preview.environment]
ANALYZE = "true"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins.inputs.audits]]
path = "index.html"
